version: "3.1"
services:
  mysql:
    image: mariadb:10.1
    volumes:
      - btc-price-db:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=database
      - MYSQL_USER=database
      - MYSQL_PASSWORD=database
    ports:
      - 3306:3306
  webserver:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - .:/application:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8910:80
    links:
      - php-fpm
  php-fpm:
    image: btc-price:latest-dev
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /application
    volumes:
      - .:/application:delegated
    links:
      - mysql
volumes:
  btc-price-db:
